language: 
  - ruby

branches:
  only:
  - enterprise
  - master

sudo: false

cache:
  bundler: true
  directories:
    - node_modules
    - "$HOME/google-cloud-sdk/"

before_install:
  - nvm install 4.6.0
  - "mkdir travis-phantomjs"
  - "wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
  - "tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs"
  - "export PATH=$PWD/travis-phantomjs:$PATH"
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - bundle install --jobs=3 --retry=3 --deployment
  - nvm use 4.6.0
  - npm install
  - cd ember-app && npm install && cd ..

before_script:
  # Install gcloud if it doesnt exist
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi

  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version

  # Authorize gcloud
  - echo $GCLOUD_KEY | base64 --decode > gcloud.p12
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud.p12

script: 
  - bundle exec rake
  - cd ember-app && ./node_modules/.bin/ember test && cd ..
  - bundle exec rake assets:precompile
  - bundle exec rake cdn:push
